import { Inter } from "next/font/google";
import "./globals.css";
import Landing from "@/components/Landing/Landing";
import Header from "@/components/Header/header";

const inter = Inter({
  weight: ["100", "400"],
  subsets: ['latin'],
});


export const metadata = {
  title: "Photography Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <Header />
        {children}
      </body>
    </html>
  );
}
